In [1]:
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [2]:
sess = tf.Session()

In [3]:
my_tensor = tf.zeros([1, 20])
sess.run(my_tensor)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [4]:
my_var = tf.Variable(tf.zeros([1, 20]))

In [6]:
sess.run(my_var.initializer) # 这个是必须的
sess.run(my_var) # 因为my_var是变量

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [7]:
row_dim = 2
col_dim = 3

In [8]:
zero_var = tf.Variable(tf.zeros([row_dim, col_dim]))
ones_var = tf.Variable(tf.ones([row_dim, col_dim]))

In [10]:
sess.run(zero_var.initializer)
sess.run(ones_var.initializer)
print(sess.run(zero_var))
sess.run(ones_var)

[[0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
zero_similar = tf.Variable(tf.zeros_like(zero_var))
ones_similar = tf.Variable(tf.ones_like(ones_var))

sess.run(zero_similar.initializer)
sess.run(ones_similar.initializer)
print(zero_similar)
print(sess.run(ones_similar))

<tf.Variable 'Variable_3:0' shape=(2, 3) dtype=float32_ref>
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
fill_var = tf.Variable(tf.fill([row_dim, col_dim], -1))
sess.run(fill_var.initializer)
print(sess.run(fill_var))

[[-1 -1 -1]
 [-1 -1 -1]]


In [16]:
const_var = tf.Variable(tf.constant([8, 6, 7, 5, 3, 0, 9]))
const_fill_var = tf.Variable(tf.constant(-1, shape=[row_dim, col_dim]))

sess.run(const_var.initializer)
sess.run(const_fill_var.initializer)

print(sess.run(const_var))
print(sess.run(const_fill_var))

[8 6 7 5 3 0 9]
[[-1 -1 -1]
 [-1 -1 -1]]


In [17]:
linear_var = tf.Variable(tf.linspace(start=0.0, stop=1.0, num=3))

sequence_var = tf.Variable(tf.range(start=6, limit=15, delta=3))

sess.run(linear_var.initializer)
sess.run(sequence_var.initializer)

print(sess.run(linear_var))
print(sess.run(sequence_var))

[0.  0.5 1. ]
[ 6  9 12]


In [21]:
rnorm_var = tf.random_normal([row_dim, col_dim], mean=0.0, stddev=10.0)
# mean 正态分布的均值 stddev 正态分页的标准差
runif_var = tf.random_uniform([row_dim, col_dim], minval=0, maxval=4)

print(sess.run(rnorm_var))
print(sess.run(runif_var))

[[-25.89252    20.000418    2.9277477]
 [  2.9264588   7.594899    2.3536947]]
[[1.1120257 3.7393594 3.4057522]
 [2.1948361 1.896668  3.215948 ]]


In [28]:
ops.reset_default_graph()

sess = tf.Session()

my_var = tf.Variable(tf.zeros([1, 20]))

# add summaries to tensorboard
merged = tf.summary.merge_all()

writer = tf.summary.FileWriter("./tmp/variable_logs", graph=sess.graph)
initialize_op = tf.global_variables_initializer()

sess.run(initialize_op)

`tensorboard --logdir=/tmp`

以上命令可以开启tensorboard

[http://0.0.0.0:6006/](http://0.0.0.0:6006/)